### ISSUE TITLE
Problem launching runserver

### ISSUE THREAD

**Issue by Seraf** [jrief/django-websocket-redis#118]
Hello,

When I launch the runserver, I have this traceback : 
```
(Cyclosible27)╭─seraf@TAGADA-LAPTOP ~/Cycloid/cyclosible  ‹master*› 
╰─➤  ./manage.py runserver                 
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

November 01, 2015 - 11:33:32
Django version 1.8.5, using settings 'cyclosible.Cyclosible.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7f23636c8488>
Traceback (most recent call last):
  File "/home/seraf/.virtualenvs/Cyclosible27/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/home/seraf/.virtualenvs/Cyclosible27/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 141, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/seraf/.virtualenvs/Cyclosible27/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 24, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/home/seraf/.virtualenvs/Cyclosible27/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 55, in get_handler
    return get_internal_wsgi_application()
  File "/home/seraf/.virtualenvs/Cyclosible27/local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 60, in get_internal_wsgi_application
    sys.exc_info()[2])
  File "/home/seraf/.virtualenvs/Cyclosible27/local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 50, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/seraf/.virtualenvs/Cyclosible27/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/mnt/DATA-LINUX/Cycloid/cyclosible/cyclosible/Cyclosible/wsgi.py", line 12, in <module>
    from ws4redis.uwsgi_runserver import uWSGIWebsocketServer
  File "/home/seraf/.virtualenvs/Cyclosible27/local/lib/python2.7/site-packages/ws4redis/uwsgi_runserver.py", line 2, in <module>
    import uwsgi
django.core.exceptions.ImproperlyConfigured: WSGI application 'cyclosible.Cyclosible.wsgi.application' could not be loaded; Error importing module: 'No module named uwsgi'
```

Here is my project : https://github.com/cycloidio/cyclosible
The wsgi file : https://github.com/cycloidio/cyclosible/blob/master/cyclosible/Cyclosible/wsgi.py

My virtualenv : 
```
amqp==1.4.7
ansible==1.9.4
anyjson==0.3.3
backports.ssl-match-hostname==3.4.0.2
billiard==3.3.0.21
boto==2.38.0
celery==3.1.19
certifi==2015.9.6.2
colorlog==2.6.0
cookies==2.2.1
coverage==4.0.1
Django==1.8.5
django-celery==3.1.17
django-filter==0.11.0
django-guardian==1.3.1
django-rest-swagger==0.3.4
django-websocket-redis==0.4.4
djangorestframework==3.3.0
ecdsa==0.13
flake8==2.5.0
funcsigs==0.4
gevent==1.0.2
greenlet==0.4.9
Jinja2==2.8
kombu==3.0.29
Markdown==2.6.3
MarkupSafe==0.23
mccabe==0.3.1
mock==1.3.0
mysqlclient==1.3.6
paramiko==1.15.3
pbr==1.8.1
pep8==1.6.2
pkginfo==1.2.1
pluggy==0.3.1
py==1.4.30
pycrypto==2.6.1
pyflakes==1.0.0
pytest==2.8.2
pytest-django==2.9.1
pytz==2015.7
PyYAML==3.11
redis==2.10.3
requests==2.8.1
requests-toolbelt==0.4.0
responses==0.5.0
six==1.10.0
stevedore==1.9.0
testfixtures==4.3.3
tornado==4.2.1
tox==2.1.1
transifex-client==0.11.1b0
twine==1.4.0
uWSGI==2.0.11.2
virtualenv==13.1.2
wheel==0.24.0
```

I don't understand which modification I could have done as I got it working before, and now, impossible to fix this error.

Any idea please ?

Thanks

**Comment by Seraf** [comment]
Sorry, the problem was on my side, WSGI_APPLICATION = 'ws4redis.django_runserver.application' has been removed from my settings.py.
