### ISSUE TITLE
TypeError: 'int' does not support the buffer interface

### ISSUE THREAD

**Issue by roidelapluie** [jrief/django-websocket-redis#135]
Hint: I am using python 3.

I get the following traceback when using ws4redis:

```
websocket.receive: Unknown error 'int' does not support the buffer interface
Other Exception: 'int' does not support the buffer interface
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/ws4redis/wsgi_server.py", line 106, in __call__
    recvmsg = RedisMessage(websocket.receive())
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/ws4redis/websocket.py", line 222, in receive
    raise e
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/ws4redis/websocket.py", line 213, in receive
    return self.read_message()
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/ws4redis/websocket.py", line 185, in read_message
    self.handle_close(header, payload)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/ws4redis/websocket.py", line 102, in handle_close
    code = struct.unpack('!H', rv[0])
TypeError: 'int' does not support the buffer interface
```

Any clue where that could come?

Thanks.

Code: https://github.com/AlexandreDecan/Lexpage/commit/fbc47a8d1f2eb9d5ffef9cf171fa02fc169eddaa
Travis: https://travis-ci.org/AlexandreDecan/Lexpage/builds/98517676

**Comment by jrief** [comment]
no, I haven't any clue either.
is ``rv[0]`` an int?

**Comment by roidelapluie** [comment]
```
type(rv):  <class 'bytes'>
rv:  b'\x03\xe9'
type(rv[0]):  <class 'int'>
rv[0]:  3
```

**Comment by roidelapluie** [comment]
Converting it to bytes with `bytes([rv[0]])` does not work:

```
struct.error: unpack requires a bytes object of length 2
```

**Comment by roidelapluie** [comment]
Maybe in py3 we can just pass the entire rv?

**Comment by jrief** [comment]
@nanuxbe any idea? I'm still using py27.

**Comment by nanuxbe** [comment]
Not sure, it looks like it is taking the first byte and casting it into an int. I'll take a closer look tomorrow.

**Comment by nanuxbe** [comment]
@roidelapluie I'm having troubles writing a test which reproduces the problem but I think I do have a fix.

Could you `pip install -U -e git+git@github.com:nanuxbe/django-websocket-redis.git@186718303fc80616c0004c56aee77eb868c67afe#egg=django_websocket_redis` and see if it fixes your problem?

**Comment by roidelapluie** [comment]
Thanks!

Here is what  get now:

```
Traceback (most recent call last):
  File "/home/roidelapluie/github/Lexpage/src/django-websocket-redis/ws4redis/wsgi_server.py", line 106, in __call__
    recvmsg = RedisMessage(websocket.receive())
  File "/home/roidelapluie/github/Lexpage/src/django-websocket-redis/ws4redis/websocket.py", line 222, in receive
    raise e
  File "/home/roidelapluie/github/Lexpage/src/django-websocket-redis/ws4redis/websocket.py", line 213, in receive
    return self.read_message()
  File "/home/roidelapluie/github/Lexpage/src/django-websocket-redis/ws4redis/websocket.py", line 185, in read_message
    self.handle_close(header, payload)
  File "/home/roidelapluie/github/Lexpage/src/django-websocket-redis/ws4redis/websocket.py", line 102, in handle_close
    code = struct.unpack('!H', '{:02X}'.format(ord(rv[0])))
TypeError: ord() expected string of length 1, but int found
```

**Comment by roidelapluie** [comment]
When I change you commit to add "    code = struct.unpack('!H', '{:02X}'.format(ord(str(rv[0])))) ", 
I get Traceback (most recent call last):
  File "/home/roidelapluie/github/Lexpage/src/django-websocket-redis/ws4redis/wsgi_server.py", line 106, in __call__
    recvmsg = RedisMessage(websocket.receive())
  File "/home/roidelapluie/github/Lexpage/src/django-websocket-redis/ws4redis/websocket.py", line 222, in receive
    raise e
  File "/home/roidelapluie/github/Lexpage/src/django-websocket-redis/ws4redis/websocket.py", line 213, in receive
    return self.read_message()
  File "/home/roidelapluie/github/Lexpage/src/django-websocket-redis/ws4redis/websocket.py", line 185, in read_message
    self.handle_close(header, payload)
  File "/home/roidelapluie/github/Lexpage/src/django-websocket-redis/ws4redis/websocket.py", line 102, in handle_close
    code = struct.unpack('!H', '{:02X}'.format(ord(str(rv[0]))))
```

```

**Comment by roidelapluie** [comment]
I will try to write a test

**Comment by roidelapluie** [comment]
Indeed it is really hard to write a test.

Those are the arguments to  self.handle_close(header, payload)
type(header) <class 'ws4redis.websocket.Header'>
header <Header fin=True opcode=8 length=2 flags=0 at 0x7f9182672ae8>
type(payload) <class 'bytes'>
payload b'\x03\xe9'

**Comment by nanuxbe** [comment]
what version of python 3 are you using?
Here is what I get when I try to reproduce your payload under python 3.4:
```
>>> payload = b'\x03\xe9'
>>> type(payload)
<type 'str'>
>>> payload = bytes(b'\x03\xe9')
>>> type(payload)
<type 'str'>
```

**Comment by roidelapluie** [comment]
Python 3.4.3

>>> payload = b'\x03\xe9'
>>> type(payload)
<class 'bytes'>
>>> payload = bytes(b'\x03\xe9')
>>> type(payload)
<class 'bytes'>

**Comment by roidelapluie** [comment]
I see your behaviour only in python2

**Comment by roidelapluie** [comment]
I opened the pull request. That error message is gone and the code is now 1001.

For some reason I still see errors in my travis tests:
```
Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.4.2/src/django-websocket-redis-origin-fix/ws4redis/wsgi_server.py", line 116, in __call__

    websocket.send(private_settings.WS4REDIS_HEARTBEAT)

  File "/home/travis/virtualenv/python3.4.2/src/django-websocket-redis-origin-fix/ws4redis/websocket.py", line 258, in send

    raise WebSocketError("Socket is dead")

ws4redis.exceptions.WebSocketError: Socket is dead

WebSocketError: Socket is dead

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.4.2/src/django-websocket-redis-origin-fix/ws4redis/websocket.py", line 256, in send

    self.send_frame(message, opcode)

  File "/home/travis/virtualenv/python3.4.2/src/django-websocket-redis-origin-fix/ws4redis/websocket.py", line 237, in send_frame

    raise WebSocketError("Connection is already closed")

ws4redis.exceptions.WebSocketError: Connection is already close
```

I will see if it is related to this ticket.


PS: Link to travis: https://travis-ci.org/AlexandreDecan/Lexpage/builds/98658769
