### ISSUE TITLE
KeyError: 'HTTP_SEC_WEBSOCKET_KEY'

### ISSUE THREAD

**Issue by cgabriel** [jrief/django-websocket-redis#54]
Hi,

I've deployed successfully django-websocket-redis, working fine. Good job!

The issue here are with certain client, specifically Safari on iOS 5.1 (which is claimed to support WebSockets) raise the error:

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/ws4redis/wsgi_server.py", line 72, in **call**
    websocket = self.upgrade_websocket(environ, start_response)

  File "/usr/local/lib/python2.7/dist-packages/ws4redis/uwsgi_runserver.py", line 52, in upgrade_websocket
    uwsgi.websocket_handshake(environ['HTTP_SEC_WEBSOCKET_KEY'], environ.get('HTTP_ORIGIN', ''))

KeyError: 'HTTP_SEC_WEBSOCKET_KEY'

Request repr() unavailable.

Any hints? Deployed with uwsgi with gevent support, behing nginx.

I can reproduce the issue regularly with the ipad above..

Thanks.

**Comment by cgabriel** [comment]
I'm closing this, too much time has passed and things had move forward.
